### ISSUE TITLE
New update broke 3 of your mods

### ISSUE THREAD

**Issue by falcon470** [OCB7D2D/OcbPinRecipes#3]
It wont even attempt to load into game with these 3 activated, the 3 are as follows, i tested them 1 at a time until it worked
ocbdensityhoe
ocbmicrosplat
and the one that hurts me thee most.....
ocbpinrecipes any way figured your github might be the quickest way to let you know

**Comment by mgreter** [comment]
Closing as not much to go by and tested ok here.
Please provide a full log in case issue persists, thx.
